// Generated by CoffeeScript 2.3.0
var AcornMixin, MagicString, Walker, acorn, dirname, isObject, mergeVisitors, nebu, relative;

({relative, dirname} = require('path'));

MagicString = require('magic-string');

AcornMixin = require('./mixin');

isObject = require('is-object');

Walker = require('./walker');

acorn = require('acorn');

nebu = exports;

nebu.parse = acorn.parse;

nebu.process = function(input, opts) {
  var ast, mapURL, mixin, output, plugins, res, walker;
  if (!Array.isArray(opts.plugins)) {
    throw Error('The `plugins` option must be an array');
  }
  // Fast plugin search by node type
  plugins = mergeVisitors(opts.plugins);
  // Let caller pass their own AST
  ast = opts.ast || acorn.parse(input, {
    ...opts.parser,
    sourceType: 'module',
    ecmaVersion: 9
  });
  // Fast mutation with sourcemap support
  output = new MagicString(input);
  // Traversal controller
  walker = new Walker(opts.state, plugins);
  // Temporarily extend Node.prototype
  mixin = AcornMixin.apply(output, walker);
  ast.depth = 0;
  walker.walk(ast);
  AcornMixin.remove(mixin);
  if (!opts.sourceMaps) {
    return output.toString();
  }
  res = {
    js: output.toString(),
    map: output.generateMap({
      includeContent: true,
      source: opts.filename,
      file: opts.generatedFile
    })
  };
  mapURL = opts.sourceMaps !== true ? res.map.toUrl() : opts.filename && opts.sourceMapTarget ? relative(dirname(opts.filename), opts.sourceMapTarget) : void 0;
  if (mapURL) {
    res.js += '\n//# sourceMappingURL=' + mapURL;
  }
  if (opts.sourceMaps !== 'inline') {
    return res;
  }
  return res.js;
};

mergeVisitors = function(plugins) {
  var arr, count, i, len, plugin, type, visitor, visitors;
  count = 0;
  visitors = Object.create(null);
  for (i = 0, len = plugins.length; i < len; i++) {
    plugin = plugins[i];
    if (isObject(plugin)) {
      for (type in plugin) {
        visitor = plugin[type];
        count += 1;
        if (arr = visitors[type]) {
          arr.push(visitor);
        } else {
          visitors[type] = [visitor];
        }
      }
    }
  }
  if (count === 0) {
    throw Error('No plugins provided a visitor');
  }
  return visitors;
};
